pub const BASE_ACCELERATION: f32 = 27.0;
pub const BASE_DECELERATION: f32 = 0.25;
pub const MOVEMENT_DAMPING: f32 = 59.;
pub const ROTATION_DAMPING: f32 = 0.07;
pub const MAX_SLOPE: f32 = 0.35;
pub const TRACK_WIDTH: f32 = 10.0;
pub const TOWER_HEIGHT: f32 = 10.0;
pub const TOWER_POSITION_BUFFER: f32 = 1.0;
pub const NUMBER_OF_PLAYERS: usize = 1; // TODO: Move this to Game Settings
pub const HIT_SHRINK_SPEED: f32 = 0.1;
pub const HIT_SPEED: f32 = 9.0;
pub const KART_HEALTH: usize = 5;
pub const BULLET_HIT_COUNT: usize = 6;
pub const KART_DIE_HIT_COUNT: usize = 12;
